### ISSUE TITLE
 id is a reserved field name for a resource 

### ISSUE THREAD

**Issue by nyankichi820** [rgl/terraform-provider-vultr#13]
failed test with latest terraform.

The cause seems to be this.
https://github.com/terraform-providers/terraform-provider-google/issues/353 
resource vultr ssh key has id property

 it may be either changing the name to another one or delete id

**Comment by casertap** [comment]
Thanks,
renaming the id property of the resourceVultrSSHKey schema solved it for me.

**Comment by rgl** [comment]
closed by https://github.com/rgl/terraform-provider-vultr/commit/2188e6541944bb2e2b9165361caf2562c184d6dd
