### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by daurnimator** [rgl/terraform-provider-vultr#3]
```
$ go build
# github.com/rgl/terraform-provider-vultr
./resource_vultr_server.go:212: server.MainIPV6 undefined (type lib.Server has no field or method MainIPV6)
./resource_vultr_server.go:271: cannot use target (type string) as type []string in field value
./resource_vultr_server.go:278: not enough arguments to return
```

**Comment by dtandersen** [comment]
This change to the client code appears to be the issue.

https://github.com/JamesClonk/vultr/commit/07e048769c5f5193d0e8bcc783d317f6ebf6af45

**Comment by clakeb** [comment]
I have it compiled with this pull request #4. My first ever go adventure but It was simple. Two lines. Hope this helps. Let me know if I need to change anything.

edit: This still isn't working as issue #2 is still present.

**Comment by rgl** [comment]
This is now fixed on master.
