### ISSUE TITLE
Hostname and Tag support

### ISSUE THREAD

**Issue by craigwillis85** [rgl/terraform-provider-vultr#6]
Hi

I've just found your provider and it works great spinning up servers on Vultr. 

I was wondering if you supported or could in future, support the possibility to add a custom `hostname` and also a custom `tag` flag when creating a server?

**Comment by rtizzy** [comment]
@craigwillis85 this has been forked and your changes have been implemented along with other improvements. You can close this here if you wish. 

I'm also working on moving to the newest version of terraform.

**Comment by rgl** [comment]
added in https://github.com/rgl/terraform-provider-vultr/commit/67189140a94e4c1b2d7489478bdca291137c89dd and https://github.com/rgl/terraform-provider-vultr/commit/f6da192b9bb05af5fa8d2072900c7a7e5abcac4d
